name: RDP Gaming GTA 5 Optimizat

on:
  workflow_dispatch:

jobs:
  rdp-gaming-gta5:
    runs-on: windows-2022
    timeout-minutes: 360

    steps:
    - name: Verificare resurse sistem
      shell: pwsh
      run: |
        Write-Host "=== Resurse System ==="
        Get-CimInstance Win32_ComputerSystem | Format-List TotalPhysicalMemory, NumberOfProcessors
        Get-CimInstance Win32_Processor | Format-List Name, NumberOfCores
        Get-WmiObject Win32_VideoController | Format-Table Name, VideoProcessor, AdapterRAM

    - name: Optimizare sistem pentru gaming
      shell: pwsh
      run: |
        # Optimizări de performanță
        powercfg /setactive 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c  # High performance
        Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "NtfsDisableLastAccessUpdate" -Value 1
        Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile" -Name "NetworkThrottlingIndex" -Value 0xFFFFFFFF
        Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games" -Name "GPU Priority" -Value 8
        Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games" -Name "Priority" -Value 6

    - name: Activează RDP
      shell: pwsh
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0

    - name: Creează utilizator pentru gaming
      shell: pwsh
      run: |
        $username = "gamer"
        $password = "GamingPass123!"
        
        # Șterge userul dacă există
        net user $username /delete 2>$null
        
        # Creează user nou
        net user $username $password /add /y
        net localgroup administrators $username /add
        net localgroup "Remote Desktop Users" $username /add
        
        Write-Output "GAMER_USER=$username" >> $env:GITHUB_ENV
        Write-Output "GAMER_PASS=$password" >> $env:GITHUB_ENV

    - name: Instalează aplicații necesare
      shell: pwsh
      run: |
        # Instalează Visual C++ Redistributables
        $vc2015 = "https://aka.ms/vs/17/release/vc_redist.x64.exe"
        Invoke-WebRequest -Uri $vc2015 -OutFile "$env:TEMP\vc_redist.x64.exe"
        Start-Process -FilePath "$env:TEMP\vc_redist.x64.exe" -ArgumentList "/install", "/quiet", "/norestart" -Wait
        
        # Instalează DirectX
        $dxwebsetup = "https://download.microsoft.com/download/8/4/A/84A35BF1-DAFE-4AE8-82AF-AD2AE20B6B14/directx_Jun2010_redist.exe"
        Invoke-WebRequest -Uri $dxwebsetup -OutFile "$env:TEMP\dxsetup.exe"

    - name: Configurează emulator GPU (Mesa3D)
      shell: pwsh
      run: |
        # Descarcă și configurează emulator software pentru GPU
        $mesaUrl = "https://github.com/pal1000/mesa-dist-win/releases/latest/download/mesa3d-23.3.1-release-msvc.7z"
        $mesaPath = "$env:TEMP\mesa.7z"
        
        Invoke-WebRequest -Uri $mesaUrl -OutFile $mesaPath
        
        # Extrage și copiază fișierele
        Expand-7Zip -ArchiveFileName $mesaPath -TargetPath "C:\mesa"
        
        # Setează variabile de mediu pentru emulator GPU
        [Environment]::SetEnvironmentVariable("GALLIUM_DRIVER", "llvmpipe", "Machine")
        [Environment]::SetEnvironmentVariable("LP_NUM_THREADS", "4", "Machine")

    - name: Optimizări grafice avansate
      shell: pwsh
      run: |
        # Configurație pentru emulare GPU optimizată
        Add-Content -Path "C:\mesa\mesa.conf" -Value @"
# Mesa3D Configuration for Gaming
gallium_drivers=swrast
default_driver=swrast
vblank_mode=0
mesa_glthread=true
"@

    - name: Configurează Tailscale
      shell: pwsh
      run: |
        $tsUrl = "https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi"
        $installerPath = "$env:TEMP\tailscale.msi"
        Invoke-WebRequest -Uri $tsUrl -OutFile $installerPath
        Start-Process msiexec.exe -ArgumentList "/i", "`"$installerPath`"", "/quiet", "/norestart" -Wait
        & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gta5-gaming-$env:GITHUB_RUN_ID

    - name: Afișează informații de conectare
      shell: pwsh
      run: |
        $tsIp = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
        Write-Host "=== INFORMATII CONECTARE GTA 5 GAMING ==="
        Write-Host "User: $env:GAMER_USER"
        Write-Host "Parola: $env:GAMER_PASS"
        Write-Host "IP Tailscale: $tsIp"
        Write-Host "Port RDP: 3389"
        Write-Host "================================"
        Write-Host "INSTRUCTIUNI GTA 5:"
        Write-Host "1. Conectează-te via RDP"
        Write-Host "2. Setări grafice: 800x600, Low, 30FPS target"
        Write-Host "3. Folosește emulatorul Mesa3D pentru randare"
        Write-Host "================================"

    - name: Menține sesiunea activă
      shell: pwsh
      run: |
        for ($i = 0; $i -lt 36; $i++) {
          Write-Host "Sesiune GTA 5 activă - $i/36"
          # Simulează activitate
          Start-Sleep 600
        }
